// ============================================================
// DUMMY DATA SERVICE — GetWork App (Phase 1)
// All data is local/in-memory. Replace with Supabase in Phase 2.
// ============================================================

import 'package:getwork/models/job_model.dart';

class DummyDataService {
  DummyDataService._();

  // ── Kathmandu area coordinates ────────────────────────────────
  static List<JobModel> getDummyJobs() {
    final now = DateTime.now();
    return [
      JobModel(
        id: 'job-001',
        title: 'Delivery Rider',
        businessId: 'biz-001',
        businessName: 'Daraz Nepal',
        latitude: 27.7172,
        longitude: 85.3240,
        address: 'Thamel, Kathmandu',
        salary: 800,
        salaryType: SalaryType.daily,
        category: JobCategory.delivery,
        description: 'Deliver parcels in Thamel area using your own bike.',
        requirements: ['Own motorcycle', 'Valid license', 'Android phone'],
        shiftDate: now,
        shiftStartTime: '09:00 AM',
        shiftEndTime: '06:00 PM',
        workersNeeded: 3,
        workersApplied: 1,
        isUrgent: true,
        createdAt: now.subtract(const Duration(hours: 2)),
        distanceKm: 0.5,
      ),
      JobModel(
        id: 'job-002',
        title: 'Supermarket Cashier',
        businessId: 'biz-002',
        businessName: 'Himalayan Mart',
        latitude: 27.7050,
        longitude: 85.3145,
        address: 'Patan Dhoka, Lalitpur',
        salary: 600,
        salaryType: SalaryType.daily,
        category: JobCategory.retail,
        description: 'Handle cash counter and assist customers.',
        requirements: ['SLC passed', 'Basic math', 'Friendly attitude'],
        shiftDate: now,
        shiftStartTime: '10:00 AM',
        shiftEndTime: '07:00 PM',
        workersNeeded: 2,
        workersApplied: 0,
        isUrgent: false,
        createdAt: now.subtract(const Duration(hours: 5)),
        distanceKm: 1.8,
      ),
      JobModel(
        id: 'job-003',
        title: 'Kitchen Helper',
        businessId: 'biz-003',
        businessName: 'OR2K Restaurant',
        latitude: 27.7185,
        longitude: 85.3280,
        address: 'Thamel, Kathmandu',
        salary: 500,
        salaryType: SalaryType.daily,
        category: JobCategory.food,
        description: 'Help in kitchen preparation and dishwashing.',
        requirements: ['No experience needed', 'Hardworking'],
        shiftDate: now,
        shiftStartTime: '08:00 AM',
        shiftEndTime: '04:00 PM',
        workersNeeded: 1,
        workersApplied: 0,
        isUrgent: false,
        createdAt: now.subtract(const Duration(hours: 1)),
        distanceKm: 0.3,
      ),
      JobModel(
        id: 'job-004',
        title: 'Office Cleaner',
        businessId: 'biz-004',
        businessName: 'NIC Asia Bank',
        latitude: 27.7200,
        longitude: 85.3180,
        address: 'New Baneshwor, Kathmandu',
        salary: 400,
        salaryType: SalaryType.daily,
        category: JobCategory.cleaning,
        description: 'Clean office premises before working hours.',
        requirements: ['Early riser', 'Experience preferred'],
        shiftDate: now,
        shiftStartTime: '06:00 AM',
        shiftEndTime: '10:00 AM',
        workersNeeded: 2,
        workersApplied: 1,
        isUrgent: false,
        createdAt: now.subtract(const Duration(hours: 3)),
        distanceKm: 2.1,
      ),
      JobModel(
        id: 'job-005',
        title: 'Event Setup Staff',
        businessId: 'biz-005',
        businessName: 'Hyatt Regency Kathmandu',
        latitude: 27.7315,
        longitude: 85.3348,
        address: 'Boudha, Kathmandu',
        salary: 1200,
        salaryType: SalaryType.daily,
        category: JobCategory.events,
        description: 'Setup chairs, tables and decorations for corporate event.',
        requirements: ['Physical fitness', 'Team player'],
        shiftDate: now.add(const Duration(days: 1)),
        shiftStartTime: '07:00 AM',
        shiftEndTime: '08:00 PM',
        workersNeeded: 10,
        workersApplied: 4,
        isUrgent: true,
        createdAt: now.subtract(const Duration(hours: 8)),
        distanceKm: 3.4,
      ),
      JobModel(
        id: 'job-006',
        title: 'Data Entry Operator',
        businessId: 'biz-006',
        businessName: 'Verisk Nepal',
        latitude: 27.7090,
        longitude: 85.3190,
        address: 'Jawalakhel, Lalitpur',
        salary: 700,
        salaryType: SalaryType.daily,
        category: JobCategory.tech,
        description: 'Enter customer data into spreadsheets. Computer skills required.',
        requirements: ['Basic computer', 'Fast typing', 'Attention to detail'],
        shiftDate: now,
        shiftStartTime: '09:00 AM',
        shiftEndTime: '05:00 PM',
        workersNeeded: 3,
        workersApplied: 2,
        isUrgent: false,
        createdAt: now.subtract(const Duration(hours: 4)),
        distanceKm: 1.2,
      ),
    ];
  }
}
